// Step 2: MarketData validation.
//
// Loads the synthetic price series (generated by data/generate_synthetic_data.py)
// and prints the computed daily mu/sigma so we can compare directly against
// the ground-truth values that script reported.
//
// Expected (from generate_synthetic_data.py, seed=42):
//   Sample daily mu:    ~0.00006610
//   Sample daily sigma: ~0.01511754

#include <iostream>
#include <iomanip>
#include "MarketData.h"

int main() {
    std::cout << "=== Multi-Asset Monte Carlo VaR Engine ===\n";
    std::cout << "Step 2: MarketData validation\n\n";

    try {
        MarketData data("../data/synthetic_prices.csv");

        std::cout << std::fixed << std::setprecision(8);
        std::cout << "Number of price observations: " << data.numObservations() << "\n";
        std::cout << "Number of log returns:        " << data.getLogReturns().size() << "\n\n";

        std::cout << "Daily mu (mean log return):     " << data.getDailyMu() << "\n";
        std::cout << "Daily sigma (std of log return): " << data.getDailySigma() << "\n\n";

        std::cout << std::setprecision(6);
        std::cout << "Annualized mu:    " << data.getAnnualizedMu() << "\n";
        std::cout << "Annualized sigma: " << data.getAnnualizedSigma() << "\n\n";

        std::cout << "First price: " << data.getPrices()[0] << "\n";
        std::cout << "Last price:  " << data.getPrices()[data.getPrices().size() - 1] << "\n";

    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
